version: '3'

services:
  jobinja:
    image: jobinja
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  sqlite:
    image: dockerpinata/sqlite
    build : .
    ports:
      - 8080:8080
    volumes:
      - ./sqlite:/var/lib/sqlite
